version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test: 
    docker:
      - image: circleci/python:3.7.7-buster
    steps:
      # Dependencies
      - checkout
      - restore_cache:
          keys:
            - venv-{{ .Branch }}-{{ checksum "setup.py" }}
            - venv-{{ .Branch }}-
            - venv-
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y libnss3 libxcomposite-dev libxcursor-dev libxi-dev libxtst-dev libxrandr-dev libxkbcommon-dev libxkbcommon-x11-0 libdbus-1-dev libasound2-dev xvfb x11-utils
      - run:
          name: Install pip modules
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -e . -r requirements.txt
            export QT_DEBUG_PLUGINS=1
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      # Tests
      - run:
          name: Pytest
          command: |
            . venv/bin/activate
            pytest -rfs -v
workflows:
  main:
    jobs:
      - build-and-test
  

