version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test: 
    docker:
      - image: circleci/python:3.7.7-buster-browsers
    steps:
      # Dependencies
      - checkout
      - restore_cache:
          keys:
            - venv-{{ .Branch }}-{{ checksum "setup.py" }}
            - venv-{{ .Branch }}-
            - venv-
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y \
              libnss3 \
              libxcomposite-dev \
              libxcursor-dev \
              libxi-dev \
              libxtst-dev \
              libxrandr-dev \
              libxkbcommon-dev \
              libxkbcommon-x11-0 \
              libdbus-1-dev \
              libasound2-dev \
              xvfb \
              x11-utils \
              herbstluftwm
      - run:
          name: Run Dummy DISPLAY
          command: |
            export DISPLAY=:99.0
            sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
            sleep 3
            sudo herbstluftwm &
            sleep 1 
      - run:
          name: Install pip modules
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -e . -r requirements.txt
            export QT_DEBUG_PLUGINS=1
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      # Tests
      - run:
          name: Pytest
          command: |
            . venv/bin/activate
            tox
workflows:
  main:
    jobs:
      - build-and-test
  

